### ISSUE TITLE
\str_lowercase:f removed in lualatex-dev

### ISSUE THREAD

**Issue by projekter** [wspr/fontspec#412]
## Description
In the developer's preview versions `lualatex-dev`, `\str_lowercase:f` seems to be removed. According to the `l3deprecation.dtx` the new command needs two underscores: `\str_lower_case:f`. Changing `fontspec-luatex.sty` to this variant works in both the normal as well as the developer variant.
## Check/indicate
- [ ] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Links to <tex.stackexchange.com> discussion if appropriate
  There seems to be a [similar issue](https://tex.stackexchange.com/questions/526626/compile-failures-after-fontspec-update), however, my `l3kernel` is both from Februar this year and `mpm` is not complaining about a required reinstallation (though I tested this, to be sure).
- [X] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{unicode-math}
\setmainfont{texgyrepagella}[
  Extension = .otf ,
  UprightFont = *-regular.otf ,
  ItalicFont  = *-italic.otf  ,
]
\begin{document}
hello \emph{hello}
\end{document}
```

**Comment by wspr** [comment]
Ignore my commit above, it has been rolled back. I wasn't paying enough attention. 

`\str_lower_case:f` is the OLD command — `\str_lowercase:f` is the new one.

I think an update to all `l3..` and `latex2e` packages in your distribution should fix the issue.

**Comment by projekter** [comment]
Sorry for the wrong report. This seems to be a MikTeX development build issue, as all my l3 packages are up-to-date (even after the update today, it is still present), and also the date of the luatex-dev format is from February 1st (rebuild right now didn't help).

**Comment by wspr** [comment]
Great to hear!
